# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.db import migrations, models
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalHospital',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the hospital', max_length=200)),
                ('code', models.CharField(blank=True, db_index=True, help_text='Hospital code or abbreviation', max_length=20, null=True)),
                ('address', models.TextField(blank=True, help_text='Complete hospital address')),
                ('phone', models.CharField(blank=True, help_text='Hospital contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Hospital contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Hospital website URL')),
                ('description', models.TextField(blank=True, help_text='Description of hospital and its specialties')),
                ('facilities', models.TextField(blank=True, help_text='Available facilities and equipment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hospital is currently accepting rotations')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Hospital',
                'verbose_name_plural': 'historical Hospitals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalRotation',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the rotation')),
                ('end_date', models.DateField(help_text='End date of the rotation')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending Approval')], default='planned', help_text='Current status of the rotation', max_length=20)),
                ('objectives', models.TextField(blank=True, help_text='Specific learning objectives for this rotation')),
                ('learning_outcomes', models.TextField(blank=True, help_text='Expected learning outcomes and competencies')),
                ('requirements', models.TextField(blank=True, help_text='Requirements and prerequisites for this rotation')),
                ('completion_certificate', models.TextField(blank=True, help_text='Completion certificate for the rotation', max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Overall feedback and comments on the rotation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes and observations')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when rotation was approved', null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('utrmc_approved_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Rotation',
                'verbose_name_plural': 'historical Rotations',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Official name of the hospital', max_length=200)),
                ('code', models.CharField(blank=True, help_text='Hospital code or abbreviation', max_length=20, null=True, unique=True)),
                ('address', models.TextField(blank=True, help_text='Complete hospital address')),
                ('phone', models.CharField(blank=True, help_text='Hospital contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Hospital contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Hospital website URL')),
                ('description', models.TextField(blank=True, help_text='Description of hospital and its specialties')),
                ('facilities', models.TextField(blank=True, help_text='Available facilities and equipment')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this hospital is currently accepting rotations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HospitalDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Department',
                'verbose_name_plural': 'Hospital Departments',
                'ordering': ['hospital__name', 'department__name'],
            },
        ),
        migrations.CreateModel(
            name='Rotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start date of the rotation')),
                ('end_date', models.DateField(help_text='End date of the rotation')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending', 'Pending Approval')], default='planned', help_text='Current status of the rotation', max_length=20)),
                ('objectives', models.TextField(blank=True, help_text='Specific learning objectives for this rotation')),
                ('learning_outcomes', models.TextField(blank=True, help_text='Expected learning outcomes and competencies')),
                ('requirements', models.TextField(blank=True, help_text='Requirements and prerequisites for this rotation')),
                ('completion_certificate', models.FileField(blank=True, help_text='Completion certificate for the rotation', null=True, upload_to='rotations/certificates/')),
                ('feedback', models.TextField(blank=True, help_text='Overall feedback and comments on the rotation')),
                ('notes', models.TextField(blank=True, help_text='Additional notes and observations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Date and time when rotation was approved', null=True)),
                ('override_reason', models.TextField(blank=True, null=True)),
                ('utrmc_approved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Rotation',
                'verbose_name_plural': 'Rotations',
                'ordering': ['-start_date', 'pg__last_name'],
            },
        ),
        migrations.CreateModel(
            name='RotationEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_type', models.CharField(choices=[('mid_rotation', 'Mid-Rotation Evaluation'), ('final', 'Final Evaluation'), ('peer', 'Peer Evaluation'), ('self', 'Self Evaluation'), ('supervisor', 'Supervisor Evaluation')], help_text='Type of evaluation', max_length=20)),
                ('score', models.IntegerField(blank=True, help_text='Numerical score (0-100)', null=True)),
                ('comments', models.TextField(blank=True, help_text='Detailed comments and feedback')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('approved', 'Approved')], default='draft', help_text='Status of the evaluation', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rotation Evaluation',
                'verbose_name_plural': 'Rotation Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
