# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotations', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rotationevaluation',
            name='evaluator',
            field=models.ForeignKey(help_text='Person conducting the evaluation', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rotationevaluation',
            name='rotation',
            field=models.ForeignKey(help_text='Rotation being evaluated', on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='rotations.rotation'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='User who approved this rotation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rotation',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this rotation assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rotation',
            name='department',
            field=models.ForeignKey(help_text='Canonical academic department where rotation takes place', on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='academics.department'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='hospital',
            field=models.ForeignKey(help_text='Hospital where rotation takes place', on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='rotations.hospital'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='pg',
            field=models.ForeignKey(help_text='Postgraduate assigned to this rotation', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rotation',
            name='source_department',
            field=models.ForeignKey(blank=True, help_text='Optional snapshot of source/home department at assignment time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_source_department', to='academics.department'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='source_hospital',
            field=models.ForeignKey(blank=True, help_text='Optional snapshot of source/home hospital at assignment time', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_source_hospital', to='rotations.hospital'),
        ),
        migrations.AddField(
            model_name='rotation',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervisor assigned to oversee this rotation', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_rotations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rotation',
            name='utrmc_approved_by',
            field=models.ForeignKey(blank=True, help_text='UTRMC admin who approved inter-hospital override', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_utrmc_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hospitaldepartment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='academics.department'),
        ),
        migrations.AddField(
            model_name='hospitaldepartment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_departments', to='rotations.hospital'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['name'], name='rotations_h_name_685955_idx'),
        ),
        migrations.AddIndex(
            model_name='hospital',
            index=models.Index(fields=['is_active'], name='rotations_h_is_acti_274d00_idx'),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who approved this rotation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this rotation assignment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Canonical academic department where rotation takes place', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department'),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='hospital',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Hospital where rotation takes place', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotations.hospital'),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='pg',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Postgraduate assigned to this rotation', limit_choices_to={'role': 'pg'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='source_department',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional snapshot of source/home department at assignment time', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department'),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='source_hospital',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Optional snapshot of source/home hospital at assignment time', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotations.hospital'),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervisor assigned to oversee this rotation', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalrotation',
            name='utrmc_approved_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='UTRMC admin who approved inter-hospital override', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalhospital',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='rotationevaluation',
            index=models.Index(fields=['rotation', 'evaluation_type'], name='rotations_r_rotatio_27e430_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationevaluation',
            index=models.Index(fields=['evaluator'], name='rotations_r_evaluat_c401aa_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationevaluation',
            index=models.Index(fields=['status'], name='rotations_r_status_9e9105_idx'),
        ),
        migrations.AddIndex(
            model_name='rotationevaluation',
            index=models.Index(fields=['created_at'], name='rotations_r_created_a4ace7_idx'),
        ),
        migrations.AddConstraint(
            model_name='rotationevaluation',
            constraint=models.CheckConstraint(check=models.Q(('score__gte', 0), ('score__lte', 100)), name='evaluation_score_range'),
        ),
        migrations.AlterUniqueTogether(
            name='rotationevaluation',
            unique_together={('rotation', 'evaluator', 'evaluation_type')},
        ),
        migrations.AddIndex(
            model_name='rotation',
            index=models.Index(fields=['pg', 'status'], name='rotations_r_pg_id_e564ea_idx'),
        ),
        migrations.AddIndex(
            model_name='rotation',
            index=models.Index(fields=['supervisor', 'status'], name='rotations_r_supervi_6755e4_idx'),
        ),
        migrations.AddIndex(
            model_name='rotation',
            index=models.Index(fields=['start_date', 'end_date'], name='rotations_r_start_d_b061f7_idx'),
        ),
        migrations.AddIndex(
            model_name='rotation',
            index=models.Index(fields=['status'], name='rotations_r_status_1e8b39_idx'),
        ),
        migrations.AddIndex(
            model_name='rotation',
            index=models.Index(fields=['hospital'], name='rotations_r_hospita_4571f1_idx'),
        ),
        migrations.AddConstraint(
            model_name='rotation',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='rotation_end_after_start'),
        ),
        migrations.AddIndex(
            model_name='hospitaldepartment',
            index=models.Index(fields=['hospital', 'department'], name='rotations_h_hospita_21d705_idx'),
        ),
        migrations.AddIndex(
            model_name='hospitaldepartment',
            index=models.Index(fields=['is_active'], name='rotations_h_is_acti_41b6c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='hospitaldepartment',
            constraint=models.UniqueConstraint(fields=('hospital', 'department'), name='uniq_hospital_department'),
        ),
    ]
