# Generated by Django 4.2.28 on 2026-03-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("rotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Official name of the hospital", max_length=200),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        help_text="Hospital code or abbreviation",
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
                ("address", models.TextField(blank=True, help_text="Complete hospital address")),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Hospital contact phone number", max_length=20
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Hospital contact email", max_length=254
                    ),
                ),
                ("website", models.URLField(blank=True, help_text="Hospital website URL")),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description of hospital and its specialties"
                    ),
                ),
                (
                    "facilities",
                    models.TextField(blank=True, help_text="Available facilities and equipment"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this hospital is currently accepting rotations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hospital",
                "verbose_name_plural": "Hospitals",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalDepartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_departments",
                        to="academics.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_departments",
                        to="rotations.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Department",
                "verbose_name_plural": "Hospital Departments",
                "ordering": ["hospital__name", "department__name"],
            },
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["name"], name="rotations_h_name_685955_idx"),
        ),
        migrations.AddIndex(
            model_name="hospital",
            index=models.Index(fields=["is_active"], name="rotations_h_is_acti_274d00_idx"),
        ),
        migrations.AddIndex(
            model_name="hospitaldepartment",
            index=models.Index(
                fields=["hospital", "department"], name="rotations_h_hospita_21d705_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hospitaldepartment",
            index=models.Index(fields=["is_active"], name="rotations_h_is_acti_41b6c1_idx"),
        ),
        migrations.AddConstraint(
            model_name="hospitaldepartment",
            constraint=models.UniqueConstraint(
                fields=("hospital", "department"), name="uniq_hospital_department"
            ),
        ),
    ]
