# Generated by Django 4.2.29 on 2026-05-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hospitaldepartment',
            options={'ordering': ['hospital__name', 'department__name'], 'verbose_name': 'Hospital-Department Matrix', 'verbose_name_plural': 'Hospital-Department Matrix'},
        ),
    ]
