# Generated by Django 4.2.29 on 2026-07-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_specialty_institution_designation_academicsession'),
        ('rotations', '0003_alter_hospitaldepartment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='institution',
            field=models.ForeignKey(blank=True, help_text='Parent institution / awarding body', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospitals', to='academics.institution'),
        ),
    ]
