# Generated by Django 4.2.27 on 2026-02-26 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused Absence')], default='present', help_text='Attendance status', max_length=20)),
                ('check_in_time', models.DateTimeField(blank=True, help_text='Time user checked in', null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-session__date', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='EligibilitySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semester', 'Semester'), ('yearly', 'Yearly')], help_text='Time period for this summary', max_length=20)),
                ('start_date', models.DateField(help_text='Start date of the period')),
                ('end_date', models.DateField(help_text='End date of the period')),
                ('total_sessions', models.IntegerField(default=0, help_text='Total number of sessions in this period')),
                ('attended_sessions', models.IntegerField(default=0, help_text='Number of sessions attended (present or late)')),
                ('percentage_present', models.FloatField(default=0.0, help_text='Percentage of sessions attended', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('is_eligible', models.BooleanField(default=False, help_text='Whether user meets eligibility threshold')),
                ('threshold_percentage', models.FloatField(default=75.0, help_text='Threshold percentage for eligibility (default 75%)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Eligibility Summary',
                'verbose_name_plural': 'Eligibility Summaries',
                'ordering': ['-start_date', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the session', max_length=200)),
                ('session_type', models.CharField(choices=[('lecture', 'Lecture'), ('clinical', 'Clinical Rotation'), ('tutorial', 'Tutorial'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('practical', 'Practical Session')], default='lecture', help_text='Type of session', max_length=20)),
                ('date', models.DateField(help_text='Date of the session')),
                ('start_time', models.TimeField(help_text='Start time of the session')),
                ('end_time', models.TimeField(help_text='End time of the session')),
                ('module_name', models.CharField(blank=True, help_text='Module or course name (if not rotation-based)', max_length=200)),
                ('location', models.CharField(blank=True, help_text='Location of the session', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', help_text='Current status of the session', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'ordering': ['-date', '-start_time'],
            },
        ),
    ]
