# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotations', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor or facilitator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taught_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='session',
            name='rotation',
            field=models.ForeignKey(blank=True, help_text='Associated rotation (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='rotations.rotation'),
        ),
        migrations.AddField(
            model_name='eligibilitysummary',
            name='user',
            field=models.ForeignKey(help_text='User (PG) this summary is for', on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_summaries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='User who recorded this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(help_text='Session this record is for', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.session'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='user',
            field=models.ForeignKey(help_text='User (PG) this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date', 'status'], name='attendance__date_ed3ec5_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['rotation'], name='attendance__rotatio_170bac_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilitysummary',
            index=models.Index(fields=['user', 'period'], name='attendance__user_id_23bcff_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilitysummary',
            index=models.Index(fields=['start_date', 'end_date'], name='attendance__start_d_e4d9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='eligibilitysummary',
            index=models.Index(fields=['is_eligible'], name='attendance__is_elig_006ebc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='eligibilitysummary',
            unique_together={('user', 'period', 'start_date', 'end_date')},
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['user', 'status'], name='attendance__user_id_ca18f0_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['session', 'status'], name='attendance__session_8dae34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('user', 'session')},
        ),
    ]
