# Generated by Django 4.2.28 on 2026-03-01 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academics", "0002_initial"),
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("IMM", "Intermediate Membership (iMM)"),
                            ("FINAL", "Final Examination"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "recommended_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recommended month in program to attempt this milestone",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Program Milestone",
                "verbose_name_plural": "Program Milestones",
                "ordering": ["program", "code"],
            },
        ),
        migrations.CreateModel(
            name="Workshop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("code", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Workshop",
                "verbose_name_plural": "Workshops",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkshopBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("capacity", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="training.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Block",
                "verbose_name_plural": "Workshop Blocks",
            },
        ),
        migrations.AddField(
            model_name="historicalprogramrotationtemplate",
            name="block_index",
            field=models.PositiveIntegerField(
                blank=True, help_text="Block within phase", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramrotationtemplate",
            name="is_mandatory",
            field=models.BooleanField(
                default=True, help_text="Is this rotation mandatory for the program?"
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramrotationtemplate",
            name="min_duration_weeks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum acceptable duration in weeks (if different from expected)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramrotationtemplate",
            name="phase_index",
            field=models.PositiveIntegerField(blank=True, help_text="Phase within year", null=True),
        ),
        migrations.AddField(
            model_name="historicalprogramrotationtemplate",
            name="requirements_json",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional requirements as structured JSON"
            ),
        ),
        migrations.AddField(
            model_name="historicalprogramrotationtemplate",
            name="year_index",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year in program (1-indexed)", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalresidenttrainingrecord",
            name="locked_program",
            field=models.BooleanField(
                default=True, help_text="Prevent program change once training starts"
            ),
        ),
        migrations.AddField(
            model_name="historicalresidenttrainingrecord",
            name="program_change_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason if program was changed (requires admin override)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalresidenttrainingrecord",
            name="restart_from_scratch_on_change",
            field=models.BooleanField(
                default=True, help_text="Reset training timeline on program change"
            ),
        ),
        migrations.AddField(
            model_name="historicalresidenttrainingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                help_text="Current enrollment status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaltrainingprogram",
            name="degree_type",
            field=models.CharField(
                choices=[
                    ("FCPS", "FCPS"),
                    ("MD", "MD"),
                    ("MS", "MS"),
                    ("Diploma", "Diploma"),
                    ("Other", "Other"),
                ],
                default="Other",
                help_text="Academic degree type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaltrainingprogram",
            name="department",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Primary department for this program",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="historicaltrainingprogram",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or administrative remarks"
            ),
        ),
        migrations.AddField(
            model_name="programrotationtemplate",
            name="block_index",
            field=models.PositiveIntegerField(
                blank=True, help_text="Block within phase", null=True
            ),
        ),
        migrations.AddField(
            model_name="programrotationtemplate",
            name="is_mandatory",
            field=models.BooleanField(
                default=True, help_text="Is this rotation mandatory for the program?"
            ),
        ),
        migrations.AddField(
            model_name="programrotationtemplate",
            name="min_duration_weeks",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Minimum acceptable duration in weeks (if different from expected)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="programrotationtemplate",
            name="phase_index",
            field=models.PositiveIntegerField(blank=True, help_text="Phase within year", null=True),
        ),
        migrations.AddField(
            model_name="programrotationtemplate",
            name="requirements_json",
            field=models.JSONField(
                blank=True, default=dict, help_text="Additional requirements as structured JSON"
            ),
        ),
        migrations.AddField(
            model_name="programrotationtemplate",
            name="year_index",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year in program (1-indexed)", null=True
            ),
        ),
        migrations.AddField(
            model_name="residenttrainingrecord",
            name="locked_program",
            field=models.BooleanField(
                default=True, help_text="Prevent program change once training starts"
            ),
        ),
        migrations.AddField(
            model_name="residenttrainingrecord",
            name="program_change_reason",
            field=models.TextField(
                blank=True,
                help_text="Reason if program was changed (requires admin override)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="residenttrainingrecord",
            name="restart_from_scratch_on_change",
            field=models.BooleanField(
                default=True, help_text="Reset training timeline on program change"
            ),
        ),
        migrations.AddField(
            model_name="residenttrainingrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("PAUSED", "Paused"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="ACTIVE",
                help_text="Current enrollment status",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="degree_type",
            field=models.CharField(
                choices=[
                    ("FCPS", "FCPS"),
                    ("MD", "MD"),
                    ("MS", "MS"),
                    ("Diploma", "Diploma"),
                    ("Other", "Other"),
                ],
                default="Other",
                help_text="Academic degree type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary department for this program",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_programs",
                to="academics.department",
            ),
        ),
        migrations.AddField(
            model_name="trainingprogram",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes or administrative remarks"
            ),
        ),
        migrations.CreateModel(
            name="WorkshopRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "block",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="training.workshopblock",
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workshop_runs_facilitated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Run",
                "verbose_name_plural": "Workshop Runs",
                "ordering": ["-run_date"],
            },
        ),
        migrations.CreateModel(
            name="ResidentThesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                (
                    "thesis_file",
                    models.FileField(blank=True, null=True, upload_to="research/thesis/"),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("final_submission_ref", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident_training_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thesis",
                        to="training.residenttrainingrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resident Thesis",
                "verbose_name_plural": "Resident Theses",
            },
        ),
        migrations.CreateModel(
            name="ResidentResearchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("topic_area", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED_TO_SUPERVISOR", "Submitted to Supervisor"),
                            ("APPROVED_BY_SUPERVISOR", "Approved by Supervisor"),
                            ("SUBMITTED_TO_UNIVERSITY", "Submitted to University"),
                            ("ACCEPTED_BY_UNIVERSITY", "Accepted by University"),
                        ],
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                (
                    "synopsis_file",
                    models.FileField(blank=True, null=True, upload_to="research/synopsis/"),
                ),
                ("synopsis_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor_feedback",
                    models.TextField(blank=True, help_text="Supervisor comments on submission"),
                ),
                (
                    "university_submission_ref",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("submitted_to_supervisor_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_to_university_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident_training_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_project",
                        to="training.residenttrainingrecord",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role__in": ["supervisor", "faculty", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervised_research_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Research Project",
                "verbose_name_plural": "Research Projects",
            },
        ),
        migrations.CreateModel(
            name="ProgramPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "allow_program_change",
                    models.BooleanField(
                        default=False,
                        help_text="Allow residents to change program after enrollment",
                    ),
                ),
                (
                    "program_change_requires_restart",
                    models.BooleanField(
                        default=True, help_text="Restart training timeline on program change"
                    ),
                ),
                (
                    "min_active_months_before_imm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum active months before iMM eligibility",
                        null=True,
                    ),
                ),
                (
                    "imm_allowed_from_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Month index from which iMM exam is allowed (e.g. halfway)",
                        null=True,
                    ),
                ),
                (
                    "final_allowed_from_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Month index from which Final exam is allowed",
                        null=True,
                    ),
                ),
                (
                    "exception_rules_text",
                    models.TextField(
                        blank=True, help_text="Free-text exceptional policy rules (non-executable)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "Program Policy",
                "verbose_name_plural": "Program Policies",
            },
        ),
        migrations.CreateModel(
            name="ProgramMilestoneResearchRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("requires_synopsis_approved", models.BooleanField(default=False)),
                ("requires_synopsis_submitted_to_university", models.BooleanField(default=False)),
                ("requires_thesis_submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "milestone",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="research_requirement",
                        to="training.programmilestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Research Requirement",
            },
        ),
        migrations.CreateModel(
            name="ProgramMilestoneLogbookRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "procedure_key",
                    models.CharField(
                        blank=True,
                        help_text="Key identifying the logbook procedure/category",
                        max_length=200,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=200)),
                ("min_entries", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logbook_requirements",
                        to="training.programmilestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Logbook Requirement",
            },
        ),
        migrations.AddField(
            model_name="programmilestone",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="milestones",
                to="training.trainingprogram",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalWorkshopRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("run_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ONGOING", "Ongoing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "block",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.workshopblock",
                    ),
                ),
                (
                    "facilitator",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Workshop Run",
                "verbose_name_plural": "historical Workshop Runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWorkshopBlock",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("capacity", models.PositiveIntegerField(default=30)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Workshop Block",
                "verbose_name_plural": "historical Workshop Blocks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalWorkshop",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("code", models.CharField(db_index=True, max_length=30)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Workshop",
                "verbose_name_plural": "historical Workshops",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResidentWorkshopCompletion",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("completed_at", models.DateField()),
                ("certificate_file", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL_UPLOAD", "Manual Upload"),
                            ("SYSTEM_GENERATED", "System Generated"),
                        ],
                        default="MANUAL_UPLOAD",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident_training_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.residenttrainingrecord",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.workshop",
                    ),
                ),
                (
                    "workshop_run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.workshoprun",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Workshop Completion",
                "verbose_name_plural": "historical Workshop Completions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResidentThesis",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_STARTED", "Not Started"),
                            ("IN_PROGRESS", "In Progress"),
                            ("SUBMITTED", "Submitted"),
                        ],
                        default="NOT_STARTED",
                        max_length=20,
                    ),
                ),
                ("thesis_file", models.TextField(blank=True, max_length=100, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("final_submission_ref", models.CharField(blank=True, max_length=200, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident_training_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.residenttrainingrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Resident Thesis",
                "verbose_name_plural": "historical Resident Theses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalResidentResearchProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("topic_area", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED_TO_SUPERVISOR", "Submitted to Supervisor"),
                            ("APPROVED_BY_SUPERVISOR", "Approved by Supervisor"),
                            ("SUBMITTED_TO_UNIVERSITY", "Submitted to University"),
                            ("ACCEPTED_BY_UNIVERSITY", "Accepted by University"),
                        ],
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                ("synopsis_file", models.TextField(blank=True, max_length=100, null=True)),
                ("synopsis_approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supervisor_feedback",
                    models.TextField(blank=True, help_text="Supervisor comments on submission"),
                ),
                (
                    "university_submission_ref",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("submitted_to_supervisor_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_to_university_at", models.DateTimeField(blank=True, null=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resident_training_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.residenttrainingrecord",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        limit_choices_to={"role__in": ["supervisor", "faculty", "admin"]},
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Research Project",
                "verbose_name_plural": "historical Research Projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramPolicy",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "allow_program_change",
                    models.BooleanField(
                        default=False,
                        help_text="Allow residents to change program after enrollment",
                    ),
                ),
                (
                    "program_change_requires_restart",
                    models.BooleanField(
                        default=True, help_text="Restart training timeline on program change"
                    ),
                ),
                (
                    "min_active_months_before_imm",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Minimum active months before iMM eligibility",
                        null=True,
                    ),
                ),
                (
                    "imm_allowed_from_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Month index from which iMM exam is allowed (e.g. halfway)",
                        null=True,
                    ),
                ),
                (
                    "final_allowed_from_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Month index from which Final exam is allowed",
                        null=True,
                    ),
                ),
                (
                    "exception_rules_text",
                    models.TextField(
                        blank=True, help_text="Free-text exceptional policy rules (non-executable)"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Program Policy",
                "verbose_name_plural": "historical Program Policies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramMilestoneWorkshopRequirement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("required_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.programmilestone",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Milestone Workshop Requirement",
                "verbose_name_plural": "historical Milestone Workshop Requirements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramMilestoneResearchRequirement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("requires_synopsis_approved", models.BooleanField(default=False)),
                ("requires_synopsis_submitted_to_university", models.BooleanField(default=False)),
                ("requires_thesis_submitted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.programmilestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Milestone Research Requirement",
                "verbose_name_plural": "historical Milestone Research Requirements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramMilestoneLogbookRequirement",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "procedure_key",
                    models.CharField(
                        blank=True,
                        help_text="Key identifying the logbook procedure/category",
                        max_length=200,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=200)),
                ("min_entries", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.programmilestone",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Milestone Logbook Requirement",
                "verbose_name_plural": "historical Milestone Logbook Requirements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalProgramMilestone",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("IMM", "Intermediate Membership (iMM)"),
                            ("FINAL", "Final Examination"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "recommended_month",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Recommended month in program to attempt this milestone",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="training.trainingprogram",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Program Milestone",
                "verbose_name_plural": "historical Program Milestones",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ResidentWorkshopCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("completed_at", models.DateField()),
                (
                    "certificate_file",
                    models.FileField(blank=True, null=True, upload_to="workshops/certificates/"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL_UPLOAD", "Manual Upload"),
                            ("SYSTEM_GENERATED", "System Generated"),
                        ],
                        default="MANUAL_UPLOAD",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resident_training_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_completions",
                        to="training.residenttrainingrecord",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="training.workshop",
                    ),
                ),
                (
                    "workshop_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completions",
                        to="training.workshoprun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Workshop Completion",
                "verbose_name_plural": "Workshop Completions",
                "ordering": ["-completed_at"],
                "indexes": [
                    models.Index(
                        fields=["resident_training_record", "workshop"],
                        name="training_re_residen_683e77_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ResidentMilestoneEligibility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NOT_READY", "Not Ready"),
                            ("PARTIALLY_READY", "Partially Ready"),
                            ("ELIGIBLE", "Eligible"),
                        ],
                        default="NOT_READY",
                        max_length=20,
                    ),
                ),
                (
                    "reasons_json",
                    models.JSONField(
                        default=list, help_text="Ordered list of unmet requirement descriptions"
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eligibilities",
                        to="training.programmilestone",
                    ),
                ),
                (
                    "resident_training_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_eligibilities",
                        to="training.residenttrainingrecord",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Eligibility",
                "verbose_name_plural": "Milestone Eligibilities",
                "ordering": ["resident_training_record", "milestone__code"],
                "unique_together": {("resident_training_record", "milestone")},
            },
        ),
        migrations.CreateModel(
            name="ProgramMilestoneWorkshopRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("required_count", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workshop_requirements",
                        to="training.programmilestone",
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestone_requirements",
                        to="training.workshop",
                    ),
                ),
            ],
            options={
                "verbose_name": "Milestone Workshop Requirement",
                "unique_together": {("milestone", "workshop")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="programmilestone",
            unique_together={("program", "code")},
        ),
    ]
