# Generated by Django 4.2.29 on 2026-05-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_logbookentry_logbookthresholdconfig_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalrotationassignment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Resident Rotation Assignment', 'verbose_name_plural': 'historical Resident Rotation Assignments'},
        ),
        migrations.AlterModelOptions(
            name='rotationassignment',
            options={'ordering': ['-start_date'], 'verbose_name': 'Resident Rotation Assignment', 'verbose_name_plural': 'Resident Rotation Assignments'},
        ),
    ]
