# Generated by Django 4.2.29 on 2026-06-26 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0006_alter_historicalrotationassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresidentresearchproject',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['SUPERVISOR', 'SUPERVISOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalresidenttrainingrecord',
            name='resident_user',
            field=models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'role__in': ['RESIDENT', 'RESIDENT']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residentresearchproject',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['SUPERVISOR', 'SUPERVISOR', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_research_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='residenttrainingrecord',
            name='resident_user',
            field=models.ForeignKey(limit_choices_to={'role__in': ['RESIDENT', 'RESIDENT']}, on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
