# Generated by Django 4.2.30 on 2026-07-27 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rotations', '0004_hospital_institution'),
        ('academics', '0008_alter_historicalsupervisorreviewqueueitem_queue_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('training', '0007_alter_historicalresidentresearchproject_supervisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='academic_session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='department',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department'),
        ),
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='training_site',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotations.hospital'),
        ),
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='academic_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_training_records', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_training_records', to='academics.department'),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='training_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_training_records', to='rotations.hospital'),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalresidenttrainingrecord',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', help_text='Current enrollment status', max_length=20),
        ),
        migrations.AlterField(
            model_name='residenttrainingrecord',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('WITHDRAWN', 'Withdrawn'), ('TRANSFERRED', 'Transferred')], default='ACTIVE', help_text='Current enrollment status', max_length=20),
        ),
    ]
