# Generated by Django 4.2.30 on 2026-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_add_academics_bridge_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='training_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='training_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
