# Generated by Django 4.2.30 on 2026-07-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_add_training_year_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresidenttrainingrecord',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residenttrainingrecord',
            name='actual_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
