# Generated by Django 5.2.17 on 2026-09-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0011_leaverequest_client_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalleaverequest',
            name='client_request_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
