# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bulk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkoperation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['user', 'created_at'], name='bulk_bulkop_user_id_55fa0c_idx'),
        ),
        migrations.AddIndex(
            model_name='bulkoperation',
            index=models.Index(fields=['operation', 'created_at'], name='bulk_bulkop_operati_225b06_idx'),
        ),
    ]
