# Generated by Django 4.2.27 on 2026-02-26 00:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Batch name (e.g., 2024 Batch)', max_length=100)),
                ('program', models.CharField(choices=[('mbbs', 'MBBS'), ('md', 'MD'), ('ms', 'MS'), ('dm', 'DM'), ('mch', 'MCh'), ('diploma', 'Diploma'), ('fellowship', 'Fellowship')], help_text='Academic program', max_length=50)),
                ('start_date', models.DateField(help_text='Batch start date')),
                ('end_date', models.DateField(help_text='Expected batch end date')),
                ('capacity', models.IntegerField(default=50, help_text='Maximum students in batch', validators=[django.core.validators.MinValueValidator(1)])),
                ('active', models.BooleanField(default=True, help_text='Is batch active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Department name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Department code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Department description')),
                ('active', models.BooleanField(default=True, help_text='Is department active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(help_text='Student roll/registration number', max_length=50, unique=True)),
                ('admission_date', models.DateField(help_text='Date of admission')),
                ('expected_graduation_date', models.DateField(blank=True, help_text='Expected graduation date', null=True)),
                ('actual_graduation_date', models.DateField(blank=True, help_text='Actual graduation date', null=True)),
                ('status', models.CharField(choices=[('admitted', 'Admitted'), ('enrolled', 'Enrolled'), ('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('withdrawn', 'Withdrawn'), ('graduated', 'Graduated'), ('expelled', 'Expelled')], default='admitted', help_text='Current enrollment status', max_length=20)),
                ('status_updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Last status change date')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, help_text='Cumulative GPA', max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('previous_institution', models.CharField(blank=True, help_text='Previous institution', max_length=200)),
                ('previous_qualification', models.CharField(blank=True, help_text='Previous qualification', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, help_text='Emergency contact person name', max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, help_text='Emergency contact phone', max_length=20)),
                ('emergency_contact_relation', models.CharField(blank=True, help_text='Relationship to student', max_length=50)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(help_text="Student's batch", on_delete=django.db.models.deletion.PROTECT, related_name='student_profiles', to='academics.batch')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['roll_number'],
            },
        ),
    ]
