# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(help_text='Linked user account', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, help_text='Department head', limit_choices_to={'role__in': ['admin', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='Batch coordinator', limit_choices_to={'role__in': ['admin', 'supervisor']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batch',
            name='department',
            field=models.ForeignKey(help_text='Department for this batch', on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.department'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['roll_number'], name='academics_s_roll_nu_ebdcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['status'], name='academics_s_status_9f57db_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['batch'], name='academics_s_batch_i_0549b2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['admission_date'], name='academics_s_admissi_8121ce_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['code'], name='academics_d_code_791f98_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['active'], name='academics_d_active_9cf6ed_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['program'], name='academics_b_program_d576e5_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['start_date', 'end_date'], name='academics_b_start_d_675282_idx'),
        ),
        migrations.AddIndex(
            model_name='batch',
            index=models.Index(fields=['active'], name='academics_b_active_3c7e78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('name', 'department', 'start_date')},
        ),
    ]
