# Generated by Django 4.2.29 on 2026-05-29 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Department / Specialty', 'verbose_name_plural': 'Departments / Specialties'},
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
