# Generated by Django 4.2.29 on 2026-07-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_alter_department_head'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Specialty name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Specialty code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Specialty description')),
                ('active', models.BooleanField(default=True, help_text='Is specialty active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='academics_s_code_b74d09_idx'), models.Index(fields=['active'], name='academics_s_active_17afd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Institution name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Institution code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Institution description')),
                ('active', models.BooleanField(default=True, help_text='Is institution active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='academics_i_code_ab9380_idx'), models.Index(fields=['active'], name='academics_i_active_369787_idx')],
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Designation name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Designation code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Designation description')),
                ('active', models.BooleanField(default=True, help_text='Is designation active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='academics_d_code_633526_idx'), models.Index(fields=['active'], name='academics_d_active_84e0a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session name', max_length=200, unique=True)),
                ('code', models.CharField(help_text='Session code', max_length=20, unique=True)),
                ('description', models.TextField(blank=True, help_text='Session description')),
                ('active', models.BooleanField(default=True, help_text='Is session active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='academics_a_code_ccb4b1_idx'), models.Index(fields=['active'], name='academics_a_active_8c6b42_idx')],
            },
        ),
    ]
