# Generated by Django 4.2.29 on 2026-07-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_logbookentry_procedurerecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsupervisorreviewqueueitem',
            name='queue_type',
            field=models.CharField(choices=[('PROFILE_REVIEW', 'Profile Review'), ('TRAINING_RECORD_REVIEW', 'Training Record Review'), ('PROGRESS_REVIEW', 'Progress Review'), ('FUTURE_EVALUATION', 'Future Evaluation'), ('EVALUATION_REVIEW', 'Evaluation Review'), ('LOGBOOK_REVIEW', 'Logbook Review')], max_length=64),
        ),
        migrations.AlterField(
            model_name='supervisorreviewqueueitem',
            name='queue_type',
            field=models.CharField(choices=[('PROFILE_REVIEW', 'Profile Review'), ('TRAINING_RECORD_REVIEW', 'Training Record Review'), ('PROGRESS_REVIEW', 'Progress Review'), ('FUTURE_EVALUATION', 'Future Evaluation'), ('EVALUATION_REVIEW', 'Evaluation Review'), ('LOGBOOK_REVIEW', 'Logbook Review')], max_length=64),
        ),
    ]
