# Generated by Django 4.2.30 on 2026-07-27 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_add_academics_bridge_fields'),
        ('academics', '0008_alter_historicalsupervisorreviewqueueitem_queue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationsubmission',
            name='training_record_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_submissions', to='training.residenttrainingrecord'),
        ),
        migrations.AddField(
            model_name='historicalevaluationsubmission',
            name='training_record_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.residenttrainingrecord'),
        ),
        migrations.AddField(
            model_name='historicallogbookentry',
            name='training_record_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.residenttrainingrecord'),
        ),
        migrations.AddField(
            model_name='historicalsupervisorreviewqueueitem',
            name='training_record_new',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='training.residenttrainingrecord'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='training_record_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='academics_logbook_entries', to='training.residenttrainingrecord'),
        ),
        migrations.AddField(
            model_name='supervisorreviewqueueitem',
            name='training_record_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_queue_items', to='training.residenttrainingrecord'),
        ),
    ]
