# Generated by Django 4.2.30 on 2026-07-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_finalize_training_record_retarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='academic_session',
        ),
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='department',
        ),
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='program',
        ),
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='resident',
        ),
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='training_site',
        ),
        migrations.RemoveField(
            model_name='residenttrainingrecord',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalResidentTrainingRecord',
        ),
        migrations.DeleteModel(
            name='ResidentTrainingRecord',
        ),
    ]
