# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotations', '0001_initial'),
        ('logbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbooktemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookstatistics',
            name='pg',
            field=models.OneToOneField(help_text='Postgraduate these statistics belong to', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='logbook_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookreview',
            name='logbook_entry',
            field=models.ForeignKey(help_text='Logbook entry being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logbook.logbookentry'),
        ),
        migrations.AddField(
            model_name='logbookreview',
            name='reviewer',
            field=models.ForeignKey(help_text='Person conducting the review', limit_choices_to={'role__in': ['supervisor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='logbook_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this entry (should be the PG)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_logbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='pg',
            field=models.ForeignKey(help_text='Postgraduate who created this entry', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='logbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='primary_diagnosis',
            field=models.ForeignKey(blank=True, help_text='Primary diagnosis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_entries', to='logbook.diagnosis'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='procedures',
            field=models.ManyToManyField(blank=True, help_text='Procedures performed or observed', related_name='logbook_entries', to='logbook.procedure'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='rotation',
            field=models.ForeignKey(blank=True, help_text='Rotation during which this case occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='rotations.rotation'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='secondary_diagnoses',
            field=models.ManyToManyField(blank=True, help_text='Secondary or differential diagnoses', related_name='secondary_entries', to='logbook.diagnosis'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='Skills demonstrated during this case', related_name='logbook_entries', to='logbook.skill'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Assigned supervising consultant', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template used for this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logbook_entries', to='logbook.logbooktemplate'),
        ),
        migrations.AddField(
            model_name='logbookentry',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='Supervisor who approved this entry', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_logbook_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalskill',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalprocedure',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallogbookreview',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicallogbookreview',
            name='logbook_entry',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Logbook entry being reviewed', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logbook.logbookentry'),
        ),
        migrations.AddField(
            model_name='historicallogbookreview',
            name='reviewer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Person conducting the review', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='common_procedures',
            field=models.ManyToManyField(blank=True, help_text='Procedures commonly associated with this diagnosis', related_name='common_diagnoses', to='logbook.procedure'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['category'], name='logbook_pro_categor_791b2c_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['difficulty_level'], name='logbook_pro_difficu_83f5f2_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['is_active'], name='logbook_pro_is_acti_b761e8_idx'),
        ),
        migrations.AddIndex(
            model_name='logbooktemplate',
            index=models.Index(fields=['template_type'], name='logbook_log_templat_69f4ca_idx'),
        ),
        migrations.AddIndex(
            model_name='logbooktemplate',
            index=models.Index(fields=['is_default'], name='logbook_log_is_defa_0eaaff_idx'),
        ),
        migrations.AddIndex(
            model_name='logbooktemplate',
            index=models.Index(fields=['is_active'], name='logbook_log_is_acti_b2f794_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookreview',
            index=models.Index(fields=['logbook_entry', 'status'], name='logbook_log_logbook_09a6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookreview',
            index=models.Index(fields=['reviewer'], name='logbook_log_reviewe_516cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookreview',
            index=models.Index(fields=['review_date'], name='logbook_log_review__3d60f8_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookreview',
            index=models.Index(fields=['status'], name='logbook_log_status_cf1b86_idx'),
        ),
        migrations.AddConstraint(
            model_name='logbookreview',
            constraint=models.UniqueConstraint(fields=('logbook_entry', 'reviewer'), name='unique_review_per_reviewer_entry'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['pg', 'date'], name='logbook_log_pg_id_92f47b_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['status'], name='logbook_log_status_3fb333_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['date'], name='logbook_log_date_2af6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['rotation'], name='logbook_log_rotatio_2736f5_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['supervisor'], name='logbook_log_supervi_0874c8_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['primary_diagnosis'], name='logbook_log_primary_5774a8_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['created_at'], name='logbook_log_created_2b3be3_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['submitted_to_supervisor_at'], name='logbook_log_submitt_0823dd_idx'),
        ),
        migrations.AddIndex(
            model_name='logbookentry',
            index=models.Index(fields=['supervisor_action_at'], name='logbook_log_supervi_097359_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['category'], name='logbook_dia_categor_4172fe_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['icd_code'], name='logbook_dia_icd_cod_5ed9be_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosis',
            index=models.Index(fields=['is_active'], name='logbook_dia_is_acti_441d42_idx'),
        ),
        migrations.AddConstraint(
            model_name='diagnosis',
            constraint=models.UniqueConstraint(fields=('name', 'category'), name='unique_diagnosis_per_category'),
        ),
    ]
