# Generated by Django 4.2.28 on 2026-03-01 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("training", "0002_phase6_academic_core"),
        ("logbook", "0002_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="logbookentry",
            name="logbook_log_rotatio_2736f5_idx",
        ),
        # Null out stale rotation_id values that reference the old sims.rotations.Rotation table
        # (those rows no longer exist after the training app replaced it with RotationAssignment)
        migrations.RunSQL(
            sql="UPDATE logbook_logbookentry SET rotation_id = NULL WHERE rotation_id IS NOT NULL",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="logbookentry",
            name="rotation",
            field=models.ForeignKey(
                blank=True,
                help_text="Rotation assignment during which this case occurred",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="logbook_entries",
                to="training.rotationassignment",
            ),
        ),
    ]
