# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('rotations', '0002_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('pg', 'Postgraduate'), ('utrmc_user', 'UTRMC User'), ('utrmc_admin', 'UTRMC Admin')], help_text='User role determines access permissions in SIMS', max_length=20)),
                ('specialty', models.CharField(blank=True, choices=[('medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('urology', 'Urology'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('radiology', 'Radiology'), ('anesthesia', 'Anesthesia'), ('pathology', 'Pathology'), ('microbiology', 'Microbiology'), ('pharmacology', 'Pharmacology'), ('community_medicine', 'Community Medicine'), ('forensic_medicine', 'Forensic Medicine'), ('other', 'Other')], help_text='Medical specialty (required for PGs and Supervisors)', max_length=100, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], help_text='Training year (required for PGs)', max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Medical council registration number', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Mark as archived instead of deleting')),
                ('archived_date', models.DateTimeField(blank=True, help_text='Date when user was archived', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_created', to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('home_department', models.ForeignKey(blank=True, help_text='Primary home department for PG users until graduation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_pgs', to='academics.department')),
                ('home_hospital', models.ForeignKey(blank=True, help_text='Primary home hospital for PG users until graduation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_pgs', to='rotations.hospital')),
                ('modified_by', models.ForeignKey(blank=True, help_text='Last admin to modify this user account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_modified', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Assigned supervisor (required for PGs)', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pgs', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'SIMS User',
                'verbose_name_plural': 'SIMS Users',
                'ordering': ['role', 'last_name', 'first_name'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('pg', 'Postgraduate'), ('utrmc_user', 'UTRMC User'), ('utrmc_admin', 'UTRMC Admin')], help_text='User role determines access permissions in SIMS', max_length=20)),
                ('specialty', models.CharField(blank=True, choices=[('medicine', 'Internal Medicine'), ('surgery', 'Surgery'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology & Obstetrics'), ('orthopedics', 'Orthopedics'), ('cardiology', 'Cardiology'), ('neurology', 'Neurology'), ('urology', 'Urology'), ('psychiatry', 'Psychiatry'), ('dermatology', 'Dermatology'), ('radiology', 'Radiology'), ('anesthesia', 'Anesthesia'), ('pathology', 'Pathology'), ('microbiology', 'Microbiology'), ('pharmacology', 'Pharmacology'), ('community_medicine', 'Community Medicine'), ('forensic_medicine', 'Forensic Medicine'), ('other', 'Other')], help_text='Medical specialty (required for PGs and Supervisors)', max_length=100, null=True)),
                ('year', models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4')], help_text='Training year (required for PGs)', max_length=10, null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Medical council registration number', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=15, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('is_archived', models.BooleanField(default=False, help_text='Mark as archived instead of deleting')),
                ('archived_date', models.DateTimeField(blank=True, help_text='Date when user was archived', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Admin who created this user account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home_department', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary home department for PG users until graduation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.department')),
                ('home_hospital', models.ForeignKey(blank=True, db_constraint=False, help_text='Primary home hospital for PG users until graduation', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotations.hospital')),
                ('modified_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Last admin to modify this user account', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, db_constraint=False, help_text='Assigned supervisor (required for PGs)', limit_choices_to={'role': 'supervisor'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical SIMS User',
                'verbose_name_plural': 'historical SIMS Users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_user_role_36d76d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['specialty'], name='users_user_special_51df32_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['supervisor'], name='users_user_supervi_cb7d54_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_user_is_acti_ddda02_idx'),
        ),
    ]
