# Generated by Django 4.2.28 on 2026-02-28 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rotations", "0002_initial"),
        ("academics", "0002_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("supervisor", "Supervisor"),
                    ("pg", "Postgraduate"),
                    ("resident", "Resident"),
                    ("faculty", "Faculty"),
                    ("utrmc_user", "UTRMC User"),
                    ("utrmc_admin", "UTRMC Admin"),
                ],
                help_text="User role determines access permissions in SIMS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Assigned supervisor (required for PGs)",
                limit_choices_to={"role__in": ["supervisor", "faculty"]},
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("supervisor", "Supervisor"),
                    ("pg", "Postgraduate"),
                    ("resident", "Resident"),
                    ("faculty", "Faculty"),
                    ("utrmc_user", "UTRMC User"),
                    ("utrmc_admin", "UTRMC Admin"),
                ],
                help_text="User role determines access permissions in SIMS",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned supervisor (required for PGs)",
                limit_choices_to={"role__in": ["supervisor", "faculty"]},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_pgs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("designation", models.CharField(blank=True, max_length=120)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["supervisor", "faculty"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="ResidentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("pgr_id", models.CharField(blank=True, max_length=60)),
                ("training_start", models.DateField()),
                ("training_end", models.DateField(blank=True, null=True)),
                ("training_level", models.CharField(blank=True, max_length=50)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role__in": ["pg", "resident"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="HospitalAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "assignment_type",
                    models.CharField(
                        choices=[
                            ("primary_training", "Primary Training"),
                            ("posting", "Posting"),
                            ("faculty_site", "Faculty Site"),
                        ],
                        max_length=30,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital_department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="rotations.hospitaldepartment",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospital_assignments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospital_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["hospital_department__hospital__name", "user__last_name"],
            },
        ),
        migrations.CreateModel(
            name="HODAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hod_assignments_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod_assignments",
                        to="academics.department",
                    ),
                ),
                (
                    "hod_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hod_assignments_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="DepartmentMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "member_type",
                    models.CharField(
                        choices=[
                            ("faculty", "Faculty"),
                            ("supervisor", "Supervisor"),
                            ("resident", "Resident"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_memberships_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="academics.department",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_memberships_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["department__name", "user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="SupervisorResidentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervision_links_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervision_links",
                        to="academics.department",
                    ),
                ),
                (
                    "resident_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resident_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supervisor_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervisor_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supervision_links_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-active", "resident_user__last_name"],
                "indexes": [
                    models.Index(
                        fields=["supervisor_user", "active"], name="users_super_supervi_c4e89f_idx"
                    ),
                    models.Index(
                        fields=["resident_user", "active"], name="users_super_residen_bb6a61_idx"
                    ),
                    models.Index(
                        fields=["department", "active"], name="users_super_departm_1b9f7d_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="supervisorresidentlink",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="supervision_link_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="supervisorresidentlink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("supervisor_user", "resident_user", "department"),
                name="uniq_active_supervision_link",
            ),
        ),
        migrations.AddIndex(
            model_name="staffprofile",
            index=models.Index(fields=["active"], name="users_staff_active_106c51_idx"),
        ),
        migrations.AddIndex(
            model_name="residentprofile",
            index=models.Index(fields=["active"], name="users_resid_active_86f7e2_idx"),
        ),
        migrations.AddIndex(
            model_name="residentprofile",
            index=models.Index(fields=["training_start"], name="users_resid_trainin_b9fc86_idx"),
        ),
        migrations.AddIndex(
            model_name="hospitalassignment",
            index=models.Index(fields=["user", "active"], name="users_hospi_user_id_ebd6bb_idx"),
        ),
        migrations.AddIndex(
            model_name="hospitalassignment",
            index=models.Index(
                fields=["hospital_department", "active"], name="users_hospi_hospita_6fde4e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hospitalassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="hospital_assignment_dates_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="hodassignment",
            index=models.Index(
                fields=["department", "active"], name="users_hodas_departm_8be3ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hodassignment",
            index=models.Index(
                fields=["hod_user", "active"], name="users_hodas_hod_use_88159e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="hodassignment",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="hod_assignment_dates_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="hodassignment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("department",),
                name="uniq_active_hod_assignment_per_department",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmembership",
            index=models.Index(
                fields=["department", "member_type", "active"],
                name="users_depar_departm_85fe35_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentmembership",
            index=models.Index(fields=["user", "active"], name="users_depar_user_id_530d57_idx"),
        ),
        migrations.AddConstraint(
            model_name="departmentmembership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("is_primary", True)),
                fields=("user",),
                name="uniq_active_primary_dept_member_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentmembership",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="dept_member_dates_valid",
            ),
        ),
    ]
