# Generated by Django 4.2.29 on 2026-04-03 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_historicaluser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5')], help_text='Training year (required for PGs)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(blank=True, choices=[('1', 'Year 1'), ('2', 'Year 2'), ('3', 'Year 3'), ('4', 'Year 4'), ('5', 'Year 5')], help_text='Training year (required for PGs)', max_length=10, null=True),
        ),
    ]
