# Generated by Django 4.2.29 on 2026-05-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluser_data_quality_and_index_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentmembership',
            options={'ordering': ['department__name', 'user__last_name', 'user__first_name'], 'verbose_name': 'User Department Membership', 'verbose_name_plural': 'User Department Memberships'},
        ),
        migrations.AlterModelOptions(
            name='hospitalassignment',
            options={'ordering': ['hospital_department__hospital__name', 'user__last_name'], 'verbose_name': 'User Hospital-Department Assignment', 'verbose_name_plural': 'User Hospital-Department Assignments'},
        ),
    ]
