# Generated by Django 4.2.29 on 2026-07-08 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_specialty_institution_designation_academicsession'),
        ('users', '0007_adminprofile_historicaladminprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresidentprofile',
            name='academic_session_ref',
            field=models.ForeignKey(blank=True, db_column='academic_session_ref', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.academicsession', to_field='code'),
        ),
        migrations.AlterField(
            model_name='historicalresidentprofile',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, db_column='specialty_ref', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.specialty', to_field='code'),
        ),
        migrations.AlterField(
            model_name='historicalsupervisorprofile',
            name='designation_ref',
            field=models.ForeignKey(blank=True, db_column='designation_ref', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.designation', to_field='code'),
        ),
        migrations.AlterField(
            model_name='historicalsupervisorprofile',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, db_column='specialty_ref', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.specialty', to_field='code'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='academic_session_ref',
            field=models.ForeignKey(blank=True, db_column='academic_session_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profiles', to='academics.academicsession', to_field='code'),
        ),
        migrations.AlterField(
            model_name='residentprofile',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, db_column='specialty_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_profiles', to='academics.specialty', to_field='code'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='designation_ref',
            field=models.ForeignKey(blank=True, db_column='designation_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_profiles', to='academics.designation', to_field='code'),
        ),
        migrations.AlterField(
            model_name='supervisorprofile',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, db_column='specialty_ref', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_profiles', to='academics.specialty', to_field='code'),
        ),
    ]
