# Generated by Django 4.2.29 on 2026-07-15 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_historicalresidentprofile_academic_session_ref_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupervisorResidentLink',
        ),
    ]
