# Generated by Django 4.2.30 on 2026-07-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_alter_historicalsupervisorreviewqueueitem_queue_type_and_more'),
        ('users', '0009_delete_supervisorresidentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Medical specialty (master-data reference; replaces the legacy `specialty` enum).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='academics.specialty', to_field='code'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty_ref',
            field=models.ForeignKey(blank=True, help_text='Medical specialty (master-data reference; replaces the legacy `specialty` enum).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='academics.specialty', to_field='code'),
        ),
    ]
