# Generated by Django 4.2.30 on 2026-07-27 19:10

from django.db import migrations

# Mirrors sims.users.models.SPECIALTY_CHOICES at the time this migration was
# written. Deliberately hardcoded here (not imported) so this migration keeps
# behaving the same way even if the app-level constant changes later.
LEGACY_SPECIALTY_CHOICES = (
    ("medicine", "Internal Medicine"),
    ("surgery", "Surgery"),
    ("pediatrics", "Pediatrics"),
    ("gynecology", "Gynecology & Obstetrics"),
    ("orthopedics", "Orthopedics"),
    ("cardiology", "Cardiology"),
    ("neurology", "Neurology"),
    ("urology", "Urology"),
    ("psychiatry", "Psychiatry"),
    ("dermatology", "Dermatology"),
    ("radiology", "Radiology"),
    ("anesthesia", "Anesthesia"),
    ("pathology", "Pathology"),
    ("microbiology", "Microbiology"),
    ("pharmacology", "Pharmacology"),
    ("community_medicine", "Community Medicine"),
    ("forensic_medicine", "Forensic Medicine"),
    ("other", "Other"),
)


def backfill_specialty_ref(apps, schema_editor):
    User = apps.get_model("users", "User")
    Specialty = apps.get_model("academics", "Specialty")

    # Ensure a Specialty row exists for every legacy enum code, so any
    # existing User.specialty value has somewhere to resolve to.
    code_to_specialty = {}
    for code, label in LEGACY_SPECIALTY_CHOICES:
        specialty, _ = Specialty.objects.get_or_create(
            code=code,
            defaults={"name": label, "active": True},
        )
        code_to_specialty[code] = specialty

    users_with_specialty = User.objects.exclude(specialty__isnull=True).exclude(specialty="")
    for user in users_with_specialty.iterator():
        specialty = code_to_specialty.get(user.specialty)
        if specialty is None:
            # Value doesn't match a known legacy code (shouldn't happen given
            # the CharField's choices constraint, but be defensive) - resolve
            # or create a Specialty row keyed on the raw value itself.
            specialty, _ = Specialty.objects.get_or_create(
                code=user.specialty[:20],
                defaults={"name": user.specialty, "active": True},
            )
        user.specialty_ref = specialty
        user.save(update_fields=["specialty_ref"])


def noop_reverse(apps, schema_editor):
    # Reversing only needs to clear the FK; the CharField data is untouched
    # and the created Specialty rows are harmless to leave in place.
    User = apps.get_model("users", "User")
    User.objects.exclude(specialty_ref__isnull=True).update(specialty_ref=None)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_specialty_ref'),
    ]

    operations = [
        migrations.RunPython(backfill_specialty_ref, noop_reverse),
    ]
