# Manually written (not autogenerated) to avoid Django's interactive
# rename-detection prompt, which would otherwise risk being answered "no"
# and turning this into a RemoveField+AddField that discards the data
# backfilled by 0011_backfill_specialty_ref.
#
# The Meta-level index on `specialty` must be dropped BEFORE the field is
# removed: SQLite rebuilds the whole table when a column is dropped, and a
# RenameIndex alone doesn't help - the rebuilt table still needs an index
# that's not referencing the about-to-be-dropped column. Drop it, do the
# field remove/rename, then recreate the index on the (renamed) new field.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_backfill_specialty_ref'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_special_51df32_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='historicaluser',
            name='specialty',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='specialty_ref',
            new_name='specialty',
        ),
        migrations.RenameField(
            model_name='historicaluser',
            old_name='specialty_ref',
            new_name='specialty',
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['specialty'], name='users_user_special_53993f_idx'),
        ),
    ]
