# Generated by Django 4.2.29 on 2026-08-21 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_drop_academics_resident_training_record'),
        ('training', '0010_add_actual_end_date'),
        ('users', '0013_alter_historicaluser_specialty_alter_user_specialty'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "ALTER TABLE users_historicalresidentprofile ADD COLUMN declaration_accepted boolean NOT NULL DEFAULT FALSE",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE users_historicalresidentprofile ADD COLUMN declaration_accepted_at timestamp with time zone NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE users_residentprofile ADD COLUMN declaration_accepted boolean NOT NULL DEFAULT FALSE",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    "ALTER TABLE users_residentprofile ADD COLUMN declaration_accepted_at timestamp with time zone NULL",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='historicalresidentprofile',
                    name='declaration_accepted',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='historicalresidentprofile',
                    name='declaration_accepted_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='residentprofile',
                    name='declaration_accepted',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='residentprofile',
                    name='declaration_accepted_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name='ResidentOnboardingDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declaration_text', models.TextField()),
                ('resident', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_declaration', to='users.residentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ResidentDocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('ONBOARDING', 'Required Now'), ('DURING_TRAINING', 'Required Later'), ('OPTIONAL', 'Optional')], default='ONBOARDING', max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_document_requirements', to='academics.department')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resident_document_requirements', to='training.trainingprogram')),
            ],
            options={
                'ordering': ['display_order', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='ResidentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='resident_documents/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('DEFERRED', 'Deferred'), ('UPLOADED', 'Uploaded'), ('PENDING_REVIEW', 'Pending Review'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('REUPLOAD_REQUIRED', 'Reupload Required')], default='NOT_STARTED', max_length=30)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='users.residentdocumentrequirement')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.residentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_resident_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requirement__display_order', 'title'],
            },
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    "CREATE UNIQUE INDEX unique_resident_document_requirement_scope ON users_residentdocumentrequirement (document_type, program_id, department_id)",
                    reverse_sql="DROP INDEX unique_resident_document_requirement_scope",
                ),
                migrations.RunSQL(
                    "CREATE UNIQUE INDEX unique_resident_requirement_fulfillment ON users_residentdocument (resident_id, requirement_id)",
                    reverse_sql="DROP INDEX unique_resident_requirement_fulfillment",
                ),
            ],
            state_operations=[
                migrations.AddConstraint(
                    model_name='residentdocumentrequirement',
                    constraint=models.UniqueConstraint(fields=('document_type', 'program', 'department'), name='unique_resident_document_requirement_scope'),
                ),
                migrations.AddConstraint(
                    model_name='residentdocument',
                    constraint=models.UniqueConstraint(fields=('resident', 'requirement'), name='unique_resident_requirement_fulfillment'),
                ),
            ],
        ),
    ]
