# Generated by Django 4.2.29 on 2026-09-02 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_historicalresidentprofile_declaration_accepted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresidentprofile',
            name='review_note',
            field=models.TextField(blank=True, help_text='Reviewer-supplied reason, set when review_status is CORRECTION_REQUIRED.'),
        ),
        migrations.AddField(
            model_name='historicalresidentprofile',
            name='review_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('CORRECTION_REQUIRED', 'Correction Required')], default='NOT_SUBMITTED', help_text='Administrative review state of the submitted onboarding profile (distinct from profile_status, which only tracks required-field completeness).', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalresidentprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalresidentprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalresidentprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='review_note',
            field=models.TextField(blank=True, help_text='Reviewer-supplied reason, set when review_status is CORRECTION_REQUIRED.'),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='review_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('CORRECTION_REQUIRED', 'Correction Required')], default='NOT_SUBMITTED', help_text='Administrative review state of the submitted onboarding profile (distinct from profile_status, which only tracks required-field completeness).', max_length=20),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='residentprofile',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
