'use client';

import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { Activity, Archive, BarChart3, BookOpen, BriefcaseBusiness, Building2, ChevronDown, ChevronLeft, ChevronRight, ClipboardList, FileText, FolderKanban, GraduationCap, LayoutDashboard, Link2, LogOut, LockKeyhole, Menu, Settings2, ShieldCheck, Users, UserRound, X } from 'lucide-react';
import { getNavForRole, AppRole, NavItem, NavSection } from '@/lib/navRegistry';

interface SidebarProps { role: string; userName: string; onLogout: () => void; }
const ICONS = { home: LayoutDashboard, users: Users, 'chart-bar': BarChart3, 'clipboard-list': ClipboardList, 'document-text': FileText, 'view-grid': FolderKanban, 'office-building': Building2, 'academic-cap': GraduationCap, briefcase: BriefcaseBusiness, collection: Archive, table: Activity, 'user-group': Users, link: Link2, 'queue-list': ClipboardList, star: Activity, folder: FolderKanban, 'document-report': BarChart3, upload: FileText, download: FileText, template: Settings2, 'book-open': BookOpen, 'folder-open': FolderKanban, refresh: Activity, 'badge-check': ShieldCheck, calendar: Activity, 'location-marker': Building2, 'check-circle': ShieldCheck, 'user-circle': UserRound, lock: LockKeyhole, 'shield-check': ShieldCheck } as const;
const ICON_COLORS: Record<string, string> = {
  home: 'text-sky-300', users: 'text-violet-300', 'academic-cap': 'text-emerald-300',
  'document-text': 'text-amber-300', link: 'text-cyan-300', 'user-group': 'text-indigo-300',
  briefcase: 'text-orange-300', 'shield-check': 'text-rose-300', collection: 'text-fuchsia-300',
  'chart-bar': 'text-lime-300', folder: 'text-yellow-300', 'book-open': 'text-blue-300',
  'queue-list': 'text-pink-300', 'badge-check': 'text-teal-300', 'location-marker': 'text-red-300',
  calendar: 'text-purple-300', 'user-circle': 'text-slate-300', lock: 'text-slate-300',
};

function NavEntry({ item, collapsed, pathname, onNavigate }: { item: NavItem; collapsed: boolean; pathname: string; onNavigate: () => void }) {
  const [open, setOpen] = useState(Boolean(item.subItems?.some((sub) => pathname === sub.href || pathname.startsWith(`${sub.href}/`))));
  const Icon = ICONS[item.icon as keyof typeof ICONS] || Activity;
  const iconColor = ICON_COLORS[item.icon] || 'text-slate-300';
  const active = item.subItems?.some((sub) => pathname === sub.href || pathname.startsWith(`${sub.href}/`)) || Boolean(item.href && (pathname === item.href || pathname.startsWith(`${item.href}/`)));
  if (item.subItems?.length) return <div><button type="button" title={collapsed ? item.label : undefined} onClick={() => setOpen((value) => !value)} className={`pg-nav-item w-full ${active ? 'pg-nav-item-active' : ''}`}><Icon className={`h-[18px] w-[18px] shrink-0 ${iconColor}`} aria-hidden="true" />{!collapsed && <><span className="truncate">{item.label}</span><ChevronDown className={`ml-auto h-4 w-4 transition-transform ${open ? 'rotate-180' : ''}`} /></>}</button>{!collapsed && open && <div className="ml-5 space-y-1 border-l border-slate-700/70 py-1 pl-3">{item.subItems.map((sub) => { const subActive = pathname === sub.href || pathname.startsWith(`${sub.href}/`); return <Link key={sub.href} href={sub.href} onClick={onNavigate} className={`block rounded-lg px-3 py-2 text-sm ${subActive ? 'bg-blue-500/15 text-blue-200' : 'text-slate-400 hover:bg-slate-800 hover:text-white'}`}>{sub.label}</Link>; })}</div>}</div>;
  return <Link href={item.href || '/dashboard'} onClick={onNavigate} title={collapsed ? item.label : undefined} className={`pg-nav-item ${active ? 'pg-nav-item-active' : ''}`}><Icon className={`h-[18px] w-[18px] shrink-0 ${iconColor}`} aria-hidden="true" />{!collapsed && <span className="truncate">{item.label}</span>}</Link>;
}
function Section({ section, collapsed, pathname, onNavigate }: { section: NavSection; collapsed: boolean; pathname: string; onNavigate: () => void }) { return <div className="mb-6"><p className={`pg-nav-section ${collapsed ? 'sr-only' : ''}`}>{section.title}</p><div className="space-y-1">{section.items.map((item) => <NavEntry key={item.label} item={item} collapsed={collapsed} pathname={pathname} onNavigate={onNavigate} />)}</div></div>; }

export default function Sidebar({ role, userName, onLogout }: SidebarProps) {
  const pathname = usePathname(); const [collapsed, setCollapsed] = useState(false); const [mobileOpen, setMobileOpen] = useState(false); const sections = getNavForRole(role as AppRole); const closeMobile = () => setMobileOpen(false);
  return <><button type="button" aria-label="Open navigation" onClick={() => setMobileOpen(true)} className="pg-mobile-menu"><Menu className="h-5 w-5" /></button>{mobileOpen && <button type="button" aria-label="Close navigation overlay" onClick={closeMobile} className="fixed inset-0 z-40 bg-slate-950/60 lg:hidden" />}<aside className={`pg-sidebar ${collapsed ? 'pg-sidebar-collapsed' : ''} ${mobileOpen ? 'pg-sidebar-mobile-open' : ''}`}><div className="flex h-20 items-center justify-between border-b border-white/10 px-5">{!collapsed && <Link href="/dashboard" className="flex items-center gap-3" onClick={closeMobile}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500 text-lg font-bold text-white shadow-lg shadow-blue-950/30">P</span><span className="text-base font-bold tracking-tight text-white">PGSIMS</span></Link>}<button type="button" onClick={() => setCollapsed((value) => !value)} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'} className="pg-icon-button ml-auto hidden lg:inline-flex">{collapsed ? <ChevronRight className="h-5 w-5" /> : <ChevronLeft className="h-5 w-5" />}</button><button type="button" onClick={closeMobile} aria-label="Close navigation" className="pg-icon-button lg:hidden"><X className="h-5 w-5" /></button></div><nav aria-label="Primary navigation" className="flex-1 overflow-y-auto px-3 py-6">{sections.map((section) => <Section key={section.title} section={section} collapsed={collapsed} pathname={pathname} onNavigate={closeMobile} />)}</nav><div className="border-t border-white/10 p-4">{!collapsed && <div className="mb-4 flex items-center gap-3 rounded-xl bg-white/5 p-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-blue-500/20 text-sm font-bold text-blue-200">{userName?.charAt(0).toUpperCase() || 'U'}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{userName || 'Account'}</p><p className="truncate text-xs text-slate-400">{role.replace('_', ' ')}</p></div></div>}<Link href="/change-password" onClick={closeMobile} className="pg-nav-item"><LockKeyhole className="h-[18px] w-[18px] shrink-0" />{!collapsed && <span>Change password</span>}</Link><button type="button" onClick={onLogout} data-testid="sidebar-logout-btn" className="pg-nav-item mt-1 w-full text-slate-400 hover:bg-red-500/10 hover:text-red-200"><LogOut className="h-[18px] w-[18px] shrink-0" />{!collapsed && <span>Sign out</span>}</button></div></aside></>;
}
