# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logbook', '0001_initial'),
        ('rotations', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who created this case', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='pg',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Postgraduate who created this case', limit_choices_to={'role': 'pg'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='primary_diagnosis',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Primary diagnosis', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='logbook.diagnosis'),
        ),
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who reviewed/approved this case', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='rotation',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Rotation during which this case occurred', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rotations.rotation'),
        ),
        migrations.AddField(
            model_name='historicalclinicalcase',
            name='supervisor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Supervising consultant', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcasecategory',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='category',
            field=models.ForeignKey(help_text='Category of the clinical case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='cases.casecategory'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='pg',
            field=models.ForeignKey(help_text='Postgraduate who created this case', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='clinical_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='primary_diagnosis',
            field=models.ForeignKey(help_text='Primary diagnosis', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_cases', to='logbook.diagnosis'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='procedures_performed',
            field=models.ManyToManyField(blank=True, help_text='Procedures performed during this case', related_name='clinical_cases', to='logbook.procedure'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed/approved this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='rotation',
            field=models.ForeignKey(blank=True, help_text='Rotation during which this case occurred', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clinical_cases', to='rotations.rotation'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='secondary_diagnoses',
            field=models.ManyToManyField(blank=True, help_text='Secondary or differential diagnoses', related_name='secondary_cases', to='logbook.diagnosis'),
        ),
        migrations.AddField(
            model_name='clinicalcase',
            name='supervisor',
            field=models.ForeignKey(blank=True, help_text='Supervising consultant', limit_choices_to={'role__in': ['supervisor', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casestatistics',
            name='pg',
            field=models.OneToOneField(help_text='Postgraduate for these statistics', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='case_statistics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='casereview',
            name='case',
            field=models.ForeignKey(help_text='Case being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='cases.clinicalcase'),
        ),
        migrations.AddField(
            model_name='casereview',
            name='reviewer',
            field=models.ForeignKey(help_text='User conducting the review', limit_choices_to={'role__in': ['supervisor', 'admin']}, on_delete=django.db.models.deletion.CASCADE, related_name='case_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='clinicalcase',
            index=models.Index(fields=['pg', 'date_encountered'], name='cases_clini_pg_id_b9dbf6_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcase',
            index=models.Index(fields=['status'], name='cases_clini_status_280b37_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcase',
            index=models.Index(fields=['category'], name='cases_clini_categor_57184b_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcase',
            index=models.Index(fields=['complexity'], name='cases_clini_complex_ddb78d_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcase',
            index=models.Index(fields=['is_featured'], name='cases_clini_is_feat_3b0c46_idx'),
        ),
        migrations.AddIndex(
            model_name='clinicalcase',
            index=models.Index(fields=['created_at'], name='cases_clini_created_4d9739_idx'),
        ),
        migrations.AddConstraint(
            model_name='clinicalcase',
            constraint=models.CheckConstraint(check=models.Q(('patient_age__gte', 0), ('patient_age__lte', 150)), name='case_valid_age'),
        ),
        migrations.AlterUniqueTogether(
            name='casereview',
            unique_together={('case', 'reviewer', 'review_date')},
        ),
    ]
