# Generated by Django 4.2.29 on 2026-07-08 21:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_historicalresidentprofile_academic_session_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentSupervisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary Supervisor'), ('CO_SUPERVISOR', 'Co-Supervisor')], default='PRIMARY', help_text='Type of supervision assignment', max_length=32)),
                ('start_date', models.DateField(help_text='Start date of the supervision assignment')),
                ('end_date', models.DateField(blank=True, help_text='End date of the supervision assignment (required if status is ENDED)', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Status of the supervision assignment', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Convenience flag to query active assignments')),
                ('notes', models.TextField(blank=True, help_text='General comments or notes')),
                ('reason_for_change', models.TextField(blank=True, help_text='Reason for modifying, ending, or changing the assignment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(help_text='The resident being supervised', on_delete=django.db.models.deletion.PROTECT, related_name='supervisor_assignments', to='users.residentprofile')),
                ('supervisor', models.ForeignKey(help_text='The assigned supervisor', on_delete=django.db.models.deletion.PROTECT, related_name='resident_assignments', to='users.supervisorprofile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalResidentSupervisorAssignment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary Supervisor'), ('CO_SUPERVISOR', 'Co-Supervisor')], default='PRIMARY', help_text='Type of supervision assignment', max_length=32)),
                ('start_date', models.DateField(help_text='Start date of the supervision assignment')),
                ('end_date', models.DateField(blank=True, help_text='End date of the supervision assignment (required if status is ENDED)', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ENDED', 'Ended'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Status of the supervision assignment', max_length=32)),
                ('is_active', models.BooleanField(default=True, help_text='Convenience flag to query active assignments')),
                ('notes', models.TextField(blank=True, help_text='General comments or notes')),
                ('reason_for_change', models.TextField(blank=True, help_text='Reason for modifying, ending, or changing the assignment')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, db_constraint=False, help_text='The resident being supervised', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.residentprofile')),
                ('supervisor', models.ForeignKey(blank=True, db_constraint=False, help_text='The assigned supervisor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.supervisorprofile')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical resident supervisor assignment',
                'verbose_name_plural': 'historical resident supervisor assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='residentsupervisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('assignment_type', 'PRIMARY'), ('is_active', True)), fields=('resident',), name='unique_active_primary_supervisor'),
        ),
        migrations.AddConstraint(
            model_name='residentsupervisorassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('resident', 'supervisor', 'assignment_type'), name='unique_active_resident_supervisor_type'),
        ),
    ]
