# Generated by Django 4.2.29 on 2026-08-21 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_alter_historicaluser_specialty_alter_user_specialty'),
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSupervisorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name_text', models.CharField(max_length=200)),
                ('department_text', models.CharField(blank=True, max_length=200)),
                ('institution_text', models.CharField(blank=True, max_length=200)),
                ('pmdc_number_text', models.CharField(blank=True, max_length=80)),
                ('email_text', models.EmailField(blank=True, max_length=254)),
                ('phone_text', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_supervisor_assignments', to='users.residentprofile')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pending_supervisor_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_pending_supervisor_requests', to='users.supervisorprofile')),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
