# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.db import migrations, models
import django.utils.timezone
import simple_history.models
import sims.certificates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Full title of the certificate', max_length=300)),
                ('certificate_number', models.CharField(blank=True, help_text='Official certificate number or ID', max_length=100)),
                ('issuing_organization', models.CharField(help_text='Organization that issued the certificate', max_length=300)),
                ('issue_date', models.DateField(help_text='Date when the certificate was issued')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when the certificate expires (if applicable)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the certificate content and training')),
                ('skills_acquired', models.TextField(blank=True, help_text='Skills and competencies acquired through this certificate')),
                ('cme_points_earned', models.PositiveIntegerField(default=0, help_text='CME points earned for this certificate')),
                ('cpd_credits_earned', models.PositiveIntegerField(default=0, help_text='CPD credits earned for this certificate')),
                ('certificate_file', models.FileField(help_text='Upload the certificate document (PDF, JPG, PNG)', upload_to=sims.certificates.models.certificate_upload_path)),
                ('additional_documents', models.FileField(blank=True, help_text='Additional supporting documents', null=True, upload_to=sims.certificates.models.additional_documents_upload_path)),
                ('verification_url', models.URLField(blank=True, help_text='URL for online verification of this certificate')),
                ('verification_code', models.CharField(blank=True, help_text='Verification code for this certificate', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this certificate has been verified')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('under_review', 'Under Review')], default='pending', help_text='Current status of the certificate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when certificate was verified', null=True)),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'ordering': ['-created_at', 'pg__last_name'],
            },
        ),
        migrations.CreateModel(
            name='CertificateReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_clarification', 'Needs Clarification')], default='pending', help_text='Review status', max_length=20)),
                ('comments', models.TextField(blank=True, help_text='Detailed review comments')),
                ('recommendations', models.TextField(blank=True, help_text='Recommendations for improvement or next steps')),
                ('required_changes', models.TextField(blank=True, help_text='Specific changes required before approval')),
                ('review_date', models.DateField(default=django.utils.timezone.now, help_text='Date when the review was conducted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Review',
                'verbose_name_plural': 'Certificate Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificateStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_certificates', models.PositiveIntegerField(default=0)),
                ('approved_certificates', models.PositiveIntegerField(default=0)),
                ('pending_certificates', models.PositiveIntegerField(default=0)),
                ('expired_certificates', models.PositiveIntegerField(default=0)),
                ('total_cme_points', models.PositiveIntegerField(default=0)),
                ('total_cpd_credits', models.PositiveIntegerField(default=0)),
                ('last_certificate_date', models.DateField(blank=True, null=True)),
                ('compliance_rate', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Statistics',
                'verbose_name_plural': 'Certificate Statistics',
            },
        ),
        migrations.CreateModel(
            name='CertificateType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the certificate type', max_length=200, unique=True)),
                ('category', models.CharField(choices=[('academic', 'Academic Qualification'), ('professional', 'Professional Certification'), ('cme', 'Continuing Medical Education'), ('cpd', 'Continuing Professional Development'), ('specialty', 'Specialty Training'), ('safety', 'Safety & Compliance'), ('skills', 'Skills & Competency'), ('other', 'Other')], default='other', help_text='Category this certificate type belongs to', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this certificate type')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this certificate is required for all PGs')),
                ('validity_period_months', models.PositiveIntegerField(blank=True, help_text='How many months this certificate is valid for (leave blank if no expiry)', null=True)),
                ('cme_points', models.PositiveIntegerField(default=0, help_text='CME points typically awarded for this certificate type')),
                ('cpd_credits', models.PositiveIntegerField(default=0, help_text='CPD credits typically awarded for this certificate type')),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisites or requirements for obtaining this certificate')),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements for this certificate type')),
                ('verification_guidelines', models.TextField(blank=True, help_text='Guidelines for verifying certificates of this type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this certificate type is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificate Type',
                'verbose_name_plural': 'Certificate Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCertificate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='Full title of the certificate', max_length=300)),
                ('certificate_number', models.CharField(blank=True, help_text='Official certificate number or ID', max_length=100)),
                ('issuing_organization', models.CharField(help_text='Organization that issued the certificate', max_length=300)),
                ('issue_date', models.DateField(help_text='Date when the certificate was issued')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when the certificate expires (if applicable)', null=True)),
                ('description', models.TextField(blank=True, help_text='Description of the certificate content and training')),
                ('skills_acquired', models.TextField(blank=True, help_text='Skills and competencies acquired through this certificate')),
                ('cme_points_earned', models.PositiveIntegerField(default=0, help_text='CME points earned for this certificate')),
                ('cpd_credits_earned', models.PositiveIntegerField(default=0, help_text='CPD credits earned for this certificate')),
                ('certificate_file', models.TextField(help_text='Upload the certificate document (PDF, JPG, PNG)', max_length=100)),
                ('additional_documents', models.TextField(blank=True, help_text='Additional supporting documents', max_length=100, null=True)),
                ('verification_url', models.URLField(blank=True, help_text='URL for online verification of this certificate')),
                ('verification_code', models.CharField(blank=True, help_text='Verification code for this certificate', max_length=100)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether this certificate has been verified')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('under_review', 'Under Review')], default='pending', help_text='Current status of the certificate', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Date and time when certificate was verified', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Certificate',
                'verbose_name_plural': 'historical Certificates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCertificateType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name of the certificate type', max_length=200)),
                ('category', models.CharField(choices=[('academic', 'Academic Qualification'), ('professional', 'Professional Certification'), ('cme', 'Continuing Medical Education'), ('cpd', 'Continuing Professional Development'), ('specialty', 'Specialty Training'), ('safety', 'Safety & Compliance'), ('skills', 'Skills & Competency'), ('other', 'Other')], default='other', help_text='Category this certificate type belongs to', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this certificate type')),
                ('is_required', models.BooleanField(default=False, help_text='Whether this certificate is required for all PGs')),
                ('validity_period_months', models.PositiveIntegerField(blank=True, help_text='How many months this certificate is valid for (leave blank if no expiry)', null=True)),
                ('cme_points', models.PositiveIntegerField(default=0, help_text='CME points typically awarded for this certificate type')),
                ('cpd_credits', models.PositiveIntegerField(default=0, help_text='CPD credits typically awarded for this certificate type')),
                ('prerequisites', models.TextField(blank=True, help_text='Prerequisites or requirements for obtaining this certificate')),
                ('requirements', models.TextField(blank=True, help_text='Specific requirements for this certificate type')),
                ('verification_guidelines', models.TextField(blank=True, help_text='Guidelines for verifying certificates of this type')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this certificate type is currently active')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Certificate Type',
                'verbose_name_plural': 'historical Certificate Types',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
