# Generated by Django 4.2.27 on 2026-02-26 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcertificatetype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='certificate_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Type of certificate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='certificates.certificatetype'),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who uploaded this certificate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='pg',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Postgraduate who earned this certificate', limit_choices_to={'role': 'pg'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcertificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='User who verified this certificate', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['category'], name='certificate_categor_126b19_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['is_required'], name='certificate_is_requ_78c29f_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatetype',
            index=models.Index(fields=['is_active'], name='certificate_is_acti_e9611d_idx'),
        ),
        migrations.AddField(
            model_name='certificatestatistics',
            name='pg',
            field=models.OneToOneField(limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_stats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificatereview',
            name='certificate',
            field=models.ForeignKey(help_text='Certificate being reviewed', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='certificates.certificate'),
        ),
        migrations.AddField(
            model_name='certificatereview',
            name='reviewer',
            field=models.ForeignKey(help_text='Person conducting the review', on_delete=django.db.models.deletion.CASCADE, related_name='certificate_reviews_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_type',
            field=models.ForeignKey(help_text='Type of certificate', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='certificates.certificatetype'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='pg',
            field=models.ForeignKey(help_text='Postgraduate who earned this certificate', limit_choices_to={'role': 'pg'}, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verified_by',
            field=models.ForeignKey(blank=True, help_text='User who verified this certificate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates_verified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='certificatereview',
            index=models.Index(fields=['certificate', 'status'], name='certificate_certifi_d99967_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatereview',
            index=models.Index(fields=['reviewer'], name='certificate_reviewe_f70c6d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatereview',
            index=models.Index(fields=['review_date'], name='certificate_review__46996d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificatereview',
            index=models.Index(fields=['created_at'], name='certificate_created_7c8fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['pg', 'status'], name='certificate_pg_id_8c0364_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['certificate_type', 'status'], name='certificate_certifi_595140_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issue_date'], name='certificate_issue_d_e50978_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['expiry_date'], name='certificate_expiry__2f5bd0_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['status'], name='certificate_status_31e804_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['is_verified'], name='certificate_is_veri_53e18d_idx'),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['issuing_organization'], name='certificate_issuing_bdd5c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='certificate',
            constraint=models.CheckConstraint(check=models.Q(('expiry_date__isnull', True), ('expiry_date__gt', models.F('issue_date')), _connector='OR'), name='certificate_expiry_after_issue'),
        ),
    ]
