#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
build="$root/android/app/build.gradle.kts"
manifest="$root/android/app/src/main/AndroidManifest.xml"
strings="$root/android/app/src/main/res/values/strings.xml"
grep -q 'applicationId = "pk.vexel.pgrcompanion"' "$build"
grep -q 'versionCode = 2' "$build"
grep -q 'versionName = "1.1.0"' "$build"
grep -q 'PGR Companion' "$strings"
grep -q 'POST_NOTIFICATIONS' "$manifest"
grep -q 'android.permission.INTERNET' "$manifest"
grep -q 'INSTITUTIONAL_API_BASE_URL' "$build"
grep -q 'https://android.pgsims.alshifalab.pk/' "$root/android/app/src/main/java/pk/vexel/pgrcompanion/InstitutionalRepository.kt" "$build"
grep -q 'InstitutionalWorkspace' "$root/android/app/src/main/java/pk/vexel/pgrcompanion/MainActivity.kt"
! grep -rn -E 'localhost|10\.0\.2\.2|example\.com|TODO endpoint|fake|mock' "$root/android/app/src/main" >/dev/null
test -f "$root/docs/android/pgr-companion-1.0.0/VERIFICATION.md"
test -f "$root/ANDROID_CURRENT_STATE.md"
test -f "$root/INSTITUTIONAL_WORKSPACE_ARCHITECTURE.md"
test -f "$root/PGR_SIMS_ANDROID_API_INTEGRATION.md"
test -f "$root/ANDROID_RELEASE_VERIFICATION.md"
echo "PGR Companion institutional release checks passed"
