# Generated by Django 4.2.28 on 2026-02-26 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rotations', '0002_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsDailyRollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('event_type', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField(default=0)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_daily_rollups', to='academics.department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_daily_rollups', to='rotations.hospital')),
            ],
            options={
                'ordering': ['-day'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('actor_role', models.CharField(blank=True, max_length=32)),
                ('entity_type', models.CharField(blank=True, max_length=64, null=True)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status_from', models.CharField(blank=True, max_length=32, null=True)),
                ('status_to', models.CharField(blank=True, max_length=32, null=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('event_key', models.CharField(blank=True, max_length=160, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='academics.department')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='rotations.hospital')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='analytics_a_event_t_69a889_idx'), models.Index(fields=['department', 'occurred_at'], name='analytics_a_departm_0700b3_idx'), models.Index(fields=['hospital', 'occurred_at'], name='analytics_a_hospita_8da40c_idx'), models.Index(fields=['request_id', 'event_type'], name='analytics_a_request_48a13a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticsevent',
            constraint=models.UniqueConstraint(condition=models.Q(('request_id__isnull', False), ('event_key__isnull', False)), fields=('request_id', 'event_type', 'event_key'), name='uniq_analytics_request_event_key'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailyrollup',
            index=models.Index(fields=['day', 'event_type'], name='analytics_a_day_6c7ae6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailyrollup',
            index=models.Index(fields=['department', 'day'], name='analytics_a_departm_f8094a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsdailyrollup',
            index=models.Index(fields=['hospital', 'day'], name='analytics_a_hospita_705d80_idx'),
        ),
        migrations.AddConstraint(
            model_name='analyticsdailyrollup',
            constraint=models.UniqueConstraint(fields=('day', 'event_type', 'department', 'hospital'), name='uniq_daily_rollup_scope'),
        ),
    ]
