# Generated by Django 4.2.28 on 2026-02-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["request_id", "event_type", "entity_id"],
                name="analytics_req_evt_entity_idx",
            ),
        ),
        migrations.CreateModel(
            name="AnalyticsValidationRejection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("source", models.CharField(db_index=True, default="track_event", max_length=32)),
                ("event_type", models.CharField(blank=True, max_length=120)),
                ("reason", models.CharField(max_length=200)),
                ("actor_role", models.CharField(blank=True, max_length=32)),
                ("department_id", models.IntegerField(blank=True, null=True)),
                ("hospital_id", models.IntegerField(blank=True, null=True)),
                ("metadata_keys", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="analyticsvalidationrejection",
            index=models.Index(fields=["event_type", "created_at"], name="analytics_rej_evt_created_idx"),
        ),
        migrations.AddIndex(
            model_name="analyticsvalidationrejection",
            index=models.Index(fields=["reason", "created_at"], name="analytics_rej_reason_created_idx"),
        ),
    ]
