# Generated by Django 5.2.17 on 2026-09-14 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_mobile_push'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mobiledevice',
            new_name='notificatio_user_id_41244e_idx',
            old_name='notificatio_user_id_9df594_idx',
        ),
    ]
