# Generated by Django 4.2.29 on 2026-05-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_kind', models.CharField(choices=[('routine_application_data', 'Routine Application Data'), ('disaster_recovery', 'Disaster Recovery')], default='routine_application_data', max_length=50)),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('safety_pre_restore', 'Safety Pre-Restore')], default='manual', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('deleted', 'Deleted')], default='pending', max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('manifest_json', models.JSONField(blank=True, null=True)),
                ('database_engine', models.CharField(blank=True, max_length=255, null=True)),
                ('media_included', models.BooleanField(default=False)),
                ('table_counts_json', models.JSONField(blank=True, null=True)),
                ('media_summary_json', models.JSONField(blank=True, null=True)),
                ('app_version', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=255, null=True)),
                ('commit_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_backups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Job',
                'verbose_name_plural': 'Backup Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restore_kind', models.CharField(choices=[('routine_application_data_restore', 'Routine Application Data Restore'), ('disaster_recovery_restore', 'Disaster Recovery Restore')], default='routine_application_data_restore', max_length=50)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='restore_uploads/')),
                ('uploaded_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('validation_failed', 'Validation Failed'), ('validation_passed', 'Validation Passed'), ('restoring', 'Restoring'), ('restored', 'Restored'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=50)),
                ('validation_result_json', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('post_restore_check_json', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('backup_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restores', to='backup_center.backupjob')),
                ('restored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_restores', to=settings.AUTH_USER_MODEL)),
                ('safety_backup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_for_restore', to='backup_center.backupjob')),
            ],
            options={
                'verbose_name': 'Restore Job',
                'verbose_name_plural': 'Restore Jobs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('routine_backup_started', 'Routine Backup Started'), ('routine_backup_completed', 'Routine Backup Completed'), ('routine_backup_failed', 'Routine Backup Failed'), ('disaster_backup_started', 'Disaster Backup Started'), ('disaster_backup_completed', 'Disaster Backup Completed'), ('disaster_backup_failed', 'Disaster Backup Failed'), ('backup_downloaded', 'Backup Downloaded'), ('backup_deleted', 'Backup Deleted'), ('backup_validated', 'Backup Validated'), ('restore_uploaded', 'Restore Uploaded'), ('restore_validation_passed', 'Restore Validation Passed'), ('restore_validation_failed', 'Restore Validation Failed'), ('restore_started', 'Restore Started'), ('safety_backup_created', 'Safety Backup Created'), ('restore_completed', 'Restore Completed'), ('restore_failed', 'Restore Failed'), ('restore_dry_run_completed', 'Restore Dry Run Completed')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('details_json', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('backup_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup_center.backupjob')),
                ('restore_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backup_center.restorejob')),
            ],
            options={
                'verbose_name': 'Backup Audit Log',
                'verbose_name_plural': 'Backup Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
