# Generated by Django 4.2.29 on 2026-05-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_center', '0002_schema_drift_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupjob',
            name='cloud_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_checksum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_checksum_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_download_status',
            field=models.CharField(default='not_uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_encryption_status',
            field=models.CharField(default='unencrypted', max_length=50),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_last_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_manifest_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_object_key',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_prefix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_upload_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_upload_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='backupjob',
            name='cloud_upload_status',
            field=models.CharField(default='not_uploaded', max_length=50),
        ),
    ]
