# Generated by Django 4.2.29 on 2026-05-31 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup_center', '0003_backupjob_cloud_bucket_backupjob_cloud_checksum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backupauditlog',
            name='action',
            field=models.CharField(choices=[('routine_backup_started', 'Routine Backup Started'), ('routine_backup_completed', 'Routine Backup Completed'), ('routine_backup_failed', 'Routine Backup Failed'), ('disaster_backup_started', 'Disaster Backup Started'), ('disaster_backup_completed', 'Disaster Backup Completed'), ('disaster_backup_failed', 'Disaster Backup Failed'), ('backup_downloaded', 'Backup Downloaded'), ('backup_deleted', 'Backup Deleted'), ('backup_validated', 'Backup Validated'), ('restore_uploaded', 'Restore Uploaded'), ('restore_validation_passed', 'Restore Validation Passed'), ('restore_validation_failed', 'Restore Validation Failed'), ('restore_started', 'Restore Started'), ('safety_backup_created', 'Safety Backup Created'), ('restore_completed', 'Restore Completed'), ('restore_failed', 'Restore Failed'), ('restore_dry_run_completed', 'Restore Dry Run Completed'), ('cloud_upload_started', 'Cloud Upload Started'), ('cloud_upload_completed', 'Cloud Upload Completed'), ('cloud_upload_failed', 'Cloud Upload Failed'), ('cloud_download_started', 'Cloud Download Started'), ('cloud_download_completed', 'Cloud Download Completed'), ('cloud_download_failed', 'Cloud Download Failed'), ('cloud_verified', 'Cloud Verified'), ('cloud_verification_failed', 'Cloud Verification Failed')], max_length=50),
        ),
    ]
