# Generated by Django 4.2.29 on 2026-06-01 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backup_center', '0004_alter_backupauditlog_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCloudConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive')], max_length=50, unique=True)),
                ('account_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('access_token_encrypted', models.TextField(blank=True, null=True)),
                ('refresh_token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expiry', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('disconnected', 'Disconnected'), ('failed', 'Failed')], default='not_connected', max_length=50)),
                ('backup_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('backup_folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_health_check_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connected_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_cloud_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Cloud Connection',
                'verbose_name_plural': 'Backup Cloud Connections',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='backupauditlog',
            name='action',
            field=models.CharField(choices=[('routine_backup_started', 'Routine Backup Started'), ('routine_backup_completed', 'Routine Backup Completed'), ('routine_backup_failed', 'Routine Backup Failed'), ('disaster_backup_started', 'Disaster Backup Started'), ('disaster_backup_completed', 'Disaster Backup Completed'), ('disaster_backup_failed', 'Disaster Backup Failed'), ('backup_downloaded', 'Backup Downloaded'), ('backup_deleted', 'Backup Deleted'), ('backup_validated', 'Backup Validated'), ('restore_uploaded', 'Restore Uploaded'), ('restore_validation_passed', 'Restore Validation Passed'), ('restore_validation_failed', 'Restore Validation Failed'), ('restore_started', 'Restore Started'), ('safety_backup_created', 'Safety Backup Created'), ('restore_completed', 'Restore Completed'), ('restore_failed', 'Restore Failed'), ('restore_dry_run_completed', 'Restore Dry Run Completed'), ('cloud_upload_started', 'Cloud Upload Started'), ('cloud_upload_completed', 'Cloud Upload Completed'), ('cloud_upload_failed', 'Cloud Upload Failed'), ('cloud_download_started', 'Cloud Download Started'), ('cloud_download_completed', 'Cloud Download Completed'), ('cloud_download_failed', 'Cloud Download Failed'), ('cloud_verified', 'Cloud Verified'), ('cloud_verification_failed', 'Cloud Verification Failed'), ('google_drive_connected', 'Google Drive Connected'), ('google_drive_disconnected', 'Google Drive Disconnected'), ('google_drive_health_check', 'Google Drive Health Check'), ('google_drive_folder_ready', 'Google Drive Folder Ready'), ('google_drive_upload_completed', 'Google Drive Upload Completed'), ('google_drive_upload_failed', 'Google Drive Upload Failed'), ('google_drive_verified', 'Google Drive Verified'), ('google_drive_verification_failed', 'Google Drive Verification Failed'), ('google_drive_download_completed', 'Google Drive Download Completed'), ('google_drive_download_failed', 'Google Drive Download Failed')], max_length=50),
        ),
        migrations.CreateModel(
            name='BackupCloudCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google_drive', 'Google Drive')], max_length=50)),
                ('remote_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_manifest_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_checksum_file_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_folder_id', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_size', models.BigIntegerField(blank=True, null=True)),
                ('local_checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('remote_checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('upload_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('upload_failed', 'Upload Failed'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('verification_failed', 'Verification Failed'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('download_failed', 'Download Failed'), ('restore_ready', 'Restore Ready')], default='not_uploaded', max_length=50)),
                ('verification_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('upload_failed', 'Upload Failed'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('verification_failed', 'Verification Failed'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('download_failed', 'Download Failed'), ('restore_ready', 'Restore Ready')], default='not_uploaded', max_length=50)),
                ('download_status', models.CharField(choices=[('not_uploaded', 'Not Uploaded'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('upload_failed', 'Upload Failed'), ('verifying', 'Verifying'), ('verified', 'Verified'), ('verification_failed', 'Verification Failed'), ('downloading', 'Downloading'), ('downloaded', 'Downloaded'), ('download_failed', 'Download Failed'), ('restore_ready', 'Restore Ready')], default='not_uploaded', max_length=50)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backup_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_copies', to='backup_center.backupjob')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='backup_center.backupcloudconnection')),
            ],
            options={
                'verbose_name': 'Backup Cloud Copy',
                'verbose_name_plural': 'Backup Cloud Copies',
                'ordering': ['-created_at'],
            },
        ),
    ]
